version: '3.7'

services:
  fl_web:
    container_name: findlook_c
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/findlook
      - static:/static
    ports: 
      - 8000:8000

volumes:
  static:
